import { SHORT_CODE_LENGTH } from '../constants';
import { buildRedirectUrl, generateShortCode, isValidShortCode } from './shortcode';

describe('generateShortCode', () => {
  it('generates a code of the default length', () => {
    expect(generateShortCode()).toHaveLength(SHORT_CODE_LENGTH);
  });

  it('honors a custom length', () => {
    expect(generateShortCode(12)).toHaveLength(12);
  });

  it('only uses characters from the unambiguous alphabet (no 0/O/1/I/l)', () => {
    const code = generateShortCode(500);
    expect(code).toMatch(/^[a-zA-Z0-9]+$/);
    expect(code).not.toMatch(/[0O1Il]/);
  });

  it('is not deterministic across calls', () => {
    const codes = new Set(Array.from({ length: 50 }, () => generateShortCode()));
    // Astronomically unlikely to collide 50 times if the RNG is wired up correctly.
    expect(codes.size).toBe(50);
  });
});

describe('isValidShortCode', () => {
  it('accepts codes generated by generateShortCode', () => {
    expect(isValidShortCode(generateShortCode())).toBe(true);
  });

  it('rejects codes that are too short', () => {
    expect(isValidShortCode('abc')).toBe(false);
  });

  it('rejects codes that are too long', () => {
    expect(isValidShortCode('a'.repeat(33))).toBe(false);
  });

  it('rejects codes with non-alphanumeric characters', () => {
    expect(isValidShortCode('abc-123')).toBe(false);
    expect(isValidShortCode('abc 123')).toBe(false);
    expect(isValidShortCode('../etc/passwd')).toBe(false);
  });
});

describe('buildRedirectUrl', () => {
  it('joins base URL and short code with /r/', () => {
    expect(buildRedirectUrl('https://qr.example.com', 'AbC1234')).toBe(
      'https://qr.example.com/r/AbC1234',
    );
  });

  it('strips a trailing slash from the base URL before joining', () => {
    expect(buildRedirectUrl('https://qr.example.com/', 'AbC1234')).toBe(
      'https://qr.example.com/r/AbC1234',
    );
  });

  it('strips multiple trailing slashes', () => {
    expect(buildRedirectUrl('https://qr.example.com///', 'AbC1234')).toBe(
      'https://qr.example.com/r/AbC1234',
    );
  });
});
