import {
  Bitcoin,
  Calendar,
  Contact,
  FileText,
  Image as ImageIcon,
  Link as LinkIcon,
  Mail,
  MapPin,
  MessageCircle,
  MessageSquare,
  Phone,
  Puzzle,
  Share2,
  Smartphone,
  Text,
  Wifi,
  type LucideIcon,
} from 'lucide-react';
import { ContentType } from '@qrgen/shared';

export const CONTENT_TYPE_ICONS: Record<ContentType, LucideIcon> = {
  [ContentType.URL]: LinkIcon,
  [ContentType.TEXT]: Text,
  [ContentType.EMAIL]: Mail,
  [ContentType.PHONE]: Phone,
  [ContentType.SMS]: MessageSquare,
  [ContentType.WHATSAPP]: MessageCircle,
  [ContentType.WIFI]: Wifi,
  [ContentType.VCARD]: Contact,
  [ContentType.LOCATION]: MapPin,
  [ContentType.EVENT]: Calendar,
  [ContentType.CRYPTO]: Bitcoin,
  [ContentType.PDF]: FileText,
  [ContentType.IMAGE]: ImageIcon,
  [ContentType.APP_STORE]: Smartphone,
  [ContentType.SOCIAL]: Share2,
  [ContentType.CUSTOM]: Puzzle,
};
